apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
       env: production

  template:
    metadata:
     name: myweb-pod 
     labels:
       env: production
    spec:
      containers:
      - name: myweb-con
        image: userprashant/image:v3